### ISSUE TITLE
String Replacement Issues in SQL Translation

### ISSUE THREAD

**Issue by takdir-rex** [multidb-dave/multidb-client-query-03#1]
Example:
- Working query: query07.sql

- Create new virtual schema/table: northwind.suppliers (virtual) --> northwind.products (physical)

- Failed query (same semantic with query07.sql):
SELECT s.SupplierID, p.ProductName, S.CompanyName FROM northwind_b.suppliers s JOIN northwind.suppliers p ON s.SupplierID = p.SupplierID WHERE s.CompanyName IN ('Exotic Liquids','Specialty Biscuits, Ltd.','Escargots Nouveaux') ORDER BY s.SupplierID

**Comment by hfahmi** [comment]
--- physical column name in northwind.suppliers is supplier_id NOT SupplierID
--- physical column name in northwind.suppliers is product_name NOT ProductName
SELECT s.SupplierID, p.product_name, S.CompanyName 
FROM northwind_b.suppliers s 
JOIN northwind.suppliers p 
ON s.SupplierID = p.supplier_id 
WHERE s.CompanyName 
IN ('Exotic Liquids','Specialty Biscuits, Ltd.','Escargots Nouveaux') 
ORDER BY s.SupplierID

--- SELECT s.SupplierID, p.ProductName, S.CompanyName
--- FROM northwind_b.suppliers s JOIN northwind.suppliers p 
--- ON s.SupplierID = p.SupplierID WHERE s.CompanyName 
--- IN ('Exotic Liquids','Specialty Biscuits, Ltd.','Escargots Nouveaux')
--- ORDER BY s.SupplierID

--- Column names which are referred in the virtual table has to correspond
--- to the physical column names of the physical table.
--- Each table may have different column names in different database source.
--- column name SupplierID for SQL Server table products
--- column name supplier_id for PostgreSQL table products
--- column name ProductName for SQL Server table products
--- column name product_name for PostgreSQL table products

**Comment by hfahmi** [comment]
Issue closed

**Comment by hfahmi** [comment]
{
  "success" : "true",
  "message" : "SQL query was created and result was fetched successfully.",
  "status" : "200",
  "errorCode" : null,
  "data" : {
    "queryId" : "0ED8.27A8.2023.0718.2028.10.614.003",
    "execTimeSec" : 3.368,
    "column" : [ "SupplierID", "product_name", "CompanyName" ],
    "numRows" : 8,
    "rows" : [ {
      "row" : [ "1", "Aniseed Syrup", "Exotic Liquids" ]
    }, {
      "row" : [ "1", "Chang", "Exotic Liquids" ]
    }, {
      "row" : [ "8", "Sir Rodney's Scones", "Specialty Biscuits, Ltd." ]
    }, {
      "row" : [ "8", "Scottish Longbreads", "Specialty Biscuits, Ltd." ]
    }, {
      "row" : [ "8", "Teatime Chocolate Biscuits", "Specialty Biscuits, Ltd." ]
    }, {
      "row" : [ "8", "Chai", "Specialty Biscuits, Ltd." ]
    }, {
      "row" : [ "8", "Sir Rodney's Marmalade", "Specialty Biscuits, Ltd." ]
    }, {
      "row" : [ "27", "Escargots de Bourgogne", "Escargots Nouveaux" ]
    } ]
  }
}

**Comment by takdir-rex** [comment]
Based on this:

Create new virtual schema/table: northwind.suppliers (virtual) --> northwind.products (physical)

Actually the "real"/physical table is still northwind.products, not northwind.suppliers (this is virtual name). So the semantic should similar with query07.sql, and the result must be similar.
